### PR TITLE
Update Nextcloud to 18.0.2

### PR DESCRIPTION
**Pull request by mtthp**
Hi @rvbuelow,

Is it okay if I merge your code into my repo ?
It seems that you've been able to add some improvements to the first draft I did and it could be beneficial to the whole community.

### CODE REVIEW

**Comment by MephistoJB** [comment]
Hi @mtthp, hi @rvbuelow 

I think it would be great to have on master repo. I am willing to contribute, too. Maybe jacques24681 can help, too (don't know how to integrate him in this discussion)

**Comment by MephistoJB** [comment]
When do you want to merge this pull request?

**Comment by rvbuelow** [comment]
Hi @mtthp 
you're welcome to merge the changes.
Cheers

**Comment by mtthp** [comment]
Sorry to answer this so late. As there aren't any great changes (mostly documentation), I decided to update the version myself in https://github.com/mtthp/hassio-addons/commit/c4f9bb48347e7ac2b7bdf3fcf0a5429e5f9ea0ea
Thanks anyway !

**Pull request closed without merging**
