### PR TITLE
Added github workflow to build and publish docker files

### LINKED ISSUE #6: docker images and ingress
Hi, I was looking at this and was wondering how open you are to help? Would you be interested in adding the images to dockerhub so the end user doesn't have to build them? also would you mind if i added ingress to this? (or try to) great work so far :D

### PR DESCRIPTION
**Pull request by sabuto**
This will build the docker images using the hassio builder. At the moment it is only set to build the amd64 image but you can build others too. The first builds to make sure there is no errors. The second will rebuild and publish. Make sure you change the docker username for yours and add a secret for the password to the repo. I have also included a shellcheck but i have commented this out for now as i dont have time to run through the errors. The build will run for commits and PR's where as the publish on runs for commits. If the build job fails the whole process is stopped so it doesn't publish faulty files. Sorry for the messy commits, if i was you i would squash and merge so there is only one commit in the history :). On my repo's i have it so it only publishes the files to Dockerhub when i do a release but as far as i can see you don't do releases so this is why i have done it this way. Any questions let me know.

### CODE REVIEW

**Comment by mtthp** [comment]
Hey @Sabuto,

Sorry to review this so late :( I will try to setup my own Docker repository to include your setup and  push automatically any new Docker image. In the meantime, this PR is on hold.

**Comment by sabuto** [comment]
np :), tbf all you need is an account it will create the repository's automatically :D

**Comment by mtthp** [comment]
Hello a few months later 👋

I finally copied the workflow from [home-assistant addons-developement repository](https://github.com/home-assistant/addons-development/blob/master/.github/workflows/builder.yml), which provides a simple way to build all architectures at once. But there is a small issue: GitHub Actions workers doesn't support the ARM architecture, so I will need to find a way around that (maybe by using my own worker).
In the meantime, `amd64` and `i386` Docker images are now available. Even if I won't merge this PR, thank you so much for the help and for showing me the way! 👍

**Comment by sabuto** [comment]
no problem :) glad i could be of help :D

**Pull request closed without merging**
